exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('users')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('users').insert([
        {
          first_name: 'Hall',
          last_name: 'Finley',
          username: 'Alexander3',
          email: 'alexanderfinley@shadease.com',
          employment: 'Employed-Mid',
          education: 'CS Degree',
          experience: '5-10 years',
          specialty: 'Dev-Ops',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 264,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Carmen',
          last_name: 'Gilliam',
          username: 'Maxwell38',
          email: 'maxwellgilliam@shadease.com',
          employment: 'Employed-Senior',
          education: 'Self-Taught',
          experience: '0-1 years',
          specialty: 'Full-Stack',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 117,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Vaughn',
          last_name: 'Burt',
          username: 'Edna7',
          email: 'ednaburt@shadease.com',
          employment: 'Hobbyist',
          education: 'CS Degree',
          experience: '5-10 years',
          specialty: 'Full-Stack',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 287,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Tamika',
          last_name: 'Pollard',
          username: 'Chavez28',
          email: 'chavezpollard@shadease.com',
          employment: 'Employed-Junior',
          education: 'Bootcamp',
          experience: '5-10 years',
          specialty: 'Machine Learning',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 202,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Susana',
          last_name: 'Hernandez',
          username: 'Amy6',
          email: 'amyhernandez@shadease.com',
          employment: 'Employed-Lead+',
          education: 'CS Degree',
          experience: '0-1 years',
          specialty: 'Dev-Ops',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 38,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Kathie',
          last_name: 'Wright',
          username: 'Brandy32',
          email: 'brandywright@shadease.com',
          employment: 'Freelancer',
          education: 'CS Degree',
          experience: '10+ years',
          specialty: 'Front-End',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 264,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Saunders',
          last_name: 'Bowen',
          username: 'Cynthia22',
          email: 'cynthiabowen@shadease.com',
          employment: 'Freelancer',
          education: 'CS Degree',
          experience: '0-1 years',
          specialty: 'Data Science',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 436,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Hooper',
          last_name: 'Dickson',
          username: 'Ellen40',
          email: 'ellendickson@shadease.com',
          employment: 'Employed-Mid',
          education: 'Self-Taught',
          experience: '1-2 years',
          specialty: 'Data Science',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 153,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Hoffman',
          last_name: 'Preston',
          username: 'Burris19',
          email: 'burrispreston@shadease.com',
          employment: 'Employed-Junior',
          education: 'CS Degree',
          experience: '2-5 years',
          specialty: 'Back-End',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 128,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Bowman',
          last_name: 'Bridges',
          username: 'Gibson27',
          email: 'gibsonbridges@shadease.com',
          employment: 'Employed-Junior',
          education: 'Bootcamp',
          experience: '5-10 years',
          specialty: 'Full-Stack',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 284,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Britney',
          last_name: 'Osborne',
          username: 'Munoz2',
          email: 'munozosborne@shadease.com',
          employment: 'Freelancer',
          education: 'Self-Taught',
          experience: '1-2 years',
          specialty: 'Machine Learning',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 152,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Henrietta',
          last_name: 'Goff',
          username: 'Ruby23',
          email: 'rubygoff@shadease.com',
          employment: 'Hobbyist',
          education: 'CS Degree',
          experience: '1-2 years',
          specialty: 'Data Science',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 146,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Russell',
          last_name: 'Guerra',
          username: 'Ayers26',
          email: 'ayersguerra@shadease.com',
          employment: 'Hobbyist',
          education: 'Bootcamp',
          experience: '2-5 years',
          specialty: 'Back-End',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 357,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Rutledge',
          last_name: 'Serrano',
          username: 'Shaffer1',
          email: 'shafferserrano@shadease.com',
          employment: 'Employed-Junior',
          education: 'Bootcamp',
          experience: '2-5 years',
          specialty: 'Dev-Ops',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 494,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Mooney',
          last_name: 'Contreras',
          username: 'Ebony33',
          email: 'ebonycontreras@shadease.com',
          employment: 'Employed-Lead+',
          education: 'Bootcamp',
          experience: '0-1 years',
          specialty: 'Machine Learning',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 450,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Marguerite',
          last_name: 'Craft',
          username: 'Ramirez4',
          email: 'ramirezcraft@shadease.com',
          employment: 'Hobbyist',
          education: 'Self-Taught',
          experience: '5-10 years',
          specialty: 'Back-End',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 409,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Raymond',
          last_name: 'Rivers',
          username: 'Candace1',
          email: 'candacerivers@shadease.com',
          employment: 'Employed-Junior',
          education: 'CS Degree',
          experience: '1-2 years',
          specialty: 'Full-Stack',
          approved: true,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 165,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Cummings',
          last_name: 'Kemp',
          username: 'Mayo10',
          email: 'mayokemp@shadease.com',
          employment: 'Employed-Lead+',
          education: 'Bootcamp',
          experience: '10+ years',
          specialty: 'Machine Learning',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 173,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Barron',
          last_name: 'Shaw',
          username: 'Klein37',
          email: 'kleinshaw@shadease.com',
          employment: 'Employed-Mid',
          education: 'Self-Taught',
          experience: '10+ years',
          specialty: 'Data Science',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 102,
          image: 'randoImg.jpeg',
        },
        {
          first_name: 'Mercado',
          last_name: 'Jimenez',
          username: 'Karina34',
          email: 'karinajimenez@shadease.com',
          employment: 'Student',
          education: 'Self-Taught',
          experience: '10+ years',
          specialty: 'Front-End',
          approved: false,
          linkedinUrl: 'https://randoLinkedIn.com',
          githubUrl: 'https://randoGitHub.com',
          personalUrl: 'https://randoPersonalSite.com',
          role: 'user',
          score: 265,
          image: 'randoImg.jpeg',
        },
      ]);
    });
};
